name = "HierarchicalUtils"
uuid = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
authors = ["Simon Mandlik <simon.mandlik@gmail.com>"]
version = "2.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DataStructures = "0.17, 0.18"
OrderedCollections = "1.3"
julia = "^1.5"
