name = "HierarchicalUtils"
uuid = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
authors = ["Simon Mandlik <simon.mandlik@gmail.com>"]
version = "1.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.17, 0.18"
julia = "1.4"
