name = "HierarchicalUtils"
uuid = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
authors = ["Simon Mandlik <simon.mandlik@gmail.com>"]
version = "2.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DataStructures = "0.18"
OrderedCollections = "1"
julia = "1.6"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = [ "Combinatorics", "Random", "Test" ]
